using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShaderDecompiler.Structures
{
    public enum OpcodeType
    {
        Nop,
        Mov,
        Add,
        Sub,
        Mad,
        Mul,
        Rcp,
        Rsq,
        Dp3,
        Dp4,
        Min,
        Max,
        Slt,
        Sge,
        Exp,
        Log,
        Lit,
        Dst,
        Lrp,
        Frc,
        M4x4,
        M4x3,
        M3x4,
        M3x3,
        M3x2,
        Call,
        Callnz,
        Loop,
        Ret,
        Endloop,
        Label,
        Dcl,
        Pow,
        Crs,
        Sgn,
        Abs,
        Nrm,
        Sincos,
        Rep,
        Endrep,
        If,
        Ifc,
        Else,
        Endif,
        Break,
        Breakc,
        Mova,
        Defb,
        Defi,

        Texcrd = 64,
        Texkill,
        Texld,
        Texbem,
        Texbeml,
        Texreg2ar,
        Texreg2gb,
        Texm3x2pad,
        Texm3x2tex,
        Texm3x3pad,
        Texm3x3tex,

        Texm3x3spec = 76,
        Texm3x3vspec,
        Expp,
        Logp,
        Cnd,
        Def,
        Texreg2rgb,
        Texdp3tex,
        Texm3x2depth,
        Texdp3,
        Texm3x3,
        Texdepth,
        Cmp,
        Bem,
        Dp2add,
        Dsx,
        Dsy,
        Texldd,
        Setp,
        Texldl,
        Breakp,

        Comment = 0xfffe,
        End = 0xffff,
    }
}
